CREATE TABLE IF NOT EXISTS public.obituaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id bigint NOT NULL UNIQUE REFERENCES public.people(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'people'
      AND column_name = 'obituary'
  ) THEN
    INSERT INTO public.obituaries (person_id, content)
    SELECT id, obituary
    FROM public.people
    WHERE obituary IS NOT NULL
      AND btrim(obituary) <> ''
    ON CONFLICT (person_id)
    DO UPDATE SET
      content = EXCLUDED.content,
      updated_at = timezone('utc', now());
  END IF;
END $$;

ALTER TABLE public.people
DROP COLUMN IF EXISTS obituary;
